name: build
on: [deployment, push]

jobs:
  pakcer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install packer

      - name: Execute pakcer build command
        run: |
          AMI_NAME="centos7-ansible-git-`date \"+%s\"`"
          TAG_NAME="centos7-ansible-git `date --date \"9 hours\" \"+%Y-%m-%d %H:%M:%S UTC+9\"`"

          packer build \
          -var "ami_name=${AMI_NAME}" \
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
          -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "tag_name=${TAG_NAME}" \
          build.json

      - name: Show Go version
        run: |
          go version

      - name: Show Packer version
        run: |
          packer version
